# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_shortcut', models.CharField(max_length=10)),
                ('board_name', models.TextField()),
                ('board_specification', models.TextField()),
                ('board_posts', models.IntegerField(default=0)),
                ('board_in_hour', models.IntegerField(default=0)),
                ('board_active_24hour', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['board_shortcut'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_tittle', models.CharField(blank=True, max_length=100)),
                ('comments_text', models.TextField()),
                ('comments_image', models.ImageField(blank=True, upload_to='')),
                ('comments_time', models.DateTimeField(auto_now_add=True)),
                ('comments_op', models.CharField(blank=True, max_length=5)),
                ('comments_answers', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_tittle', models.CharField(blank=True, max_length=255)),
                ('thread_text', models.TextField()),
                ('thread_image', models.ImageField(blank=True, upload_to='')),
                ('thread_time', models.DateTimeField(auto_now_add=True)),
                ('thread_score', models.IntegerField(default=0)),
                ('thread_answers', models.TextField(blank=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageboard.Board')),
            ],
            options={
                'ordering': ['-thread_time'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageboard.Thread'),
        ),
    ]
