# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('imageboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_board', models.CharField(max_length=1024)),
                ('expire_date', models.DateTimeField()),
                ('active', models.CharField(blank=True, max_length=1024)),
                ('thread', models.TextField(blank=True)),
                ('session_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
            ],
        ),
    ]
